import React from 'react'
import MatOrItem from './MatOrItem';

function MatOrItems() {
  const categories = [
    {
      title: "Cardiologie",
      num_questions: 11,
      dps : [
        {
          id: 3066,
          title:"DP 1",
          lastAssessed: "Jan 6, 2022",
          item: "",
          matiere: "",
          lastScore: 4,
        },
        {
          id: 3065,
          title:"DP 2",
          lastAssessed: "",
          item: "",
          matiere: "Cardiologie, Pneumologie, Néphrologie",
          lastScore: null,
        },
        {
          id: 3064,
          title:"DP 3",
          lastAssessed: "",
          item: "",
          matiere: "Cardiologie, Pneumologie, Néphrologie",
          lastScore: null,
        },
        {
          id: 3063,
          title:"DP 4",
          lastAssessed: "Jan 5, 2022",
          item: "",
          matiere: "",
          lastScore: 20,
        },
        {
          id: 3062,
          title:"DP 5",
          lastAssessed: "Jan 5, 2022",
          item: "154. Dissection Aortique",
          matiere: "",
          lastScore: 20,
        },
        {
          id: 3061,
          title:"DP 6",
          lastAssessed: "Jan 4, 2022",
          item: "",
          matiere: "",
          lastScore: 4,
        },
        {
          id: 3060,
          title:"LCA 1",
          lastAssessed: "",
          item: "",
          matiere: "",
          lastScore: null,
        },
        {
          id: 3059,
          title:"LCA 2",
          lastAssessed: "",
          item: "",
          matiere: "",
          lastScore: null,
        },
        {
          id: 3058,
          title:"DP 7",
          lastAssessed: "Jan 3, 2022",
          item: "",
          matiere: "",
          lastScore: 4,
        },
        {
          id: 3057,
          title:"DP 8",
          lastAssessed: "Jan 3, 2022",
          item: "",
          matiere: "",
          lastScore: 4,
        },
      ]
    },
    {
      title: "Néphrologie",
      num_questions: 12,
      dps : [
        {
          id: 3066,
          title:"DP 1",
          lastAssessed: "Jan 6, 2022",
          item: "",
          matiere: "",
          lastScore: 4,
        },
        {
          id: 3065,
          title:"DP 2",
          lastAssessed: "",
          item: "",
          matiere: "Cardiologie, Pneumologie, Néphrologie",
          lastScore: null,
        },
        {
          id: 3064,
          title:"DP 3",
          lastAssessed: "",
          item: "",
          matiere: "Cardiologie, Pneumologie, Néphrologie",
          lastScore: null,
        },
        {
          id: 3063,
          title:"DP 4",
          lastAssessed: "Jan 5, 2022",
          item: "",
          matiere: "",
          lastScore: 20,
        },
        {
          id: 3062,
          title:"DP 5",
          lastAssessed: "Jan 5, 2022",
          item: "154. Dissection Aortique",
          matiere: "",
          lastScore: 20,
        },
        {
          id: 3061,
          title:"DP 6",
          lastAssessed: "Jan 4, 2022",
          item: "",
          matiere: "",
          lastScore: 4,
        },
        {
          id: 3060,
          title:"LCA 1",
          lastAssessed: "",
          item: "",
          matiere: "",
          lastScore: null,
        },
        {
          id: 3059,
          title:"LCA 2",
          lastAssessed: "",
          item: "",
          matiere: "",
          lastScore: null,
        },
        {
          id: 3058,
          title:"DP 7",
          lastAssessed: "Jan 3, 2022",
          item: "",
          matiere: "",
          lastScore: 4,
        },
        {
          id: 3057,
          title:"DP 8",
          lastAssessed: "Jan 3, 2022",
          item: "",
          matiere: "",
          lastScore: 4,
        },
      ]
    },
    {
      title: "Urologie",
      num_questions: 56,
      color: "pink",
      dps : [
        {
          id: 3066,
          title:"DP 1",
          lastAssessed: "Jan 6, 2022",
          item: "",
          matiere: "",
          lastScore: 4,
        },
        {
          id: 3065,
          title:"DP 2",
          lastAssessed: "",
          item: "",
          matiere: "Cardiologie, Pneumologie, Néphrologie",
          lastScore: null,
        },
        {
          id: 3064,
          title:"DP 3",
          lastAssessed: "",
          item: "",
          matiere: "Cardiologie, Pneumologie, Néphrologie",
          lastScore: null,
        },
        {
          id: 3063,
          title:"DP 4",
          lastAssessed: "Jan 5, 2022",
          item: "",
          matiere: "",
          lastScore: 20,
        },
        {
          id: 3062,
          title:"DP 5",
          lastAssessed: "Jan 5, 2022",
          item: "154. Dissection Aortique",
          matiere: "",
          lastScore: 20,
        },
        {
          id: 3061,
          title:"DP 6",
          lastAssessed: "Jan 4, 2022",
          item: "",
          matiere: "",
          lastScore: 4,
        },
        {
          id: 3060,
          title:"LCA 1",
          lastAssessed: "",
          item: "",
          matiere: "",
          lastScore: null,
        },
        {
          id: 3059,
          title:"LCA 2",
          lastAssessed: "",
          item: "",
          matiere: "",
          lastScore: null,
        },
        {
          id: 3058,
          title:"DP 7",
          lastAssessed: "Jan 3, 2022",
          item: "",
          matiere: "",
          lastScore: 4,
        },
        {
          id: 3057,
          title:"DP 8",
          lastAssessed: "Jan 3, 2022",
          item: "",
          matiere: "",
          lastScore: 4,
        },
      ]
    },
    {
      title: "Dermatologie",
      num_questions: 3,
      dps : [
        {
          id: 3066,
          title:"DP 1",
          lastAssessed: "Jan 6, 2022",
          item: "",
          matiere: "",
          lastScore: 4,
        },
        {
          id: 3065,
          title:"DP 2",
          lastAssessed: "",
          item: "",
          matiere: "Cardiologie, Pneumologie, Néphrologie",
          lastScore: null,
        },
        {
          id: 3064,
          title:"DP 3",
          lastAssessed: "",
          item: "",
          matiere: "Cardiologie, Pneumologie, Néphrologie",
          lastScore: null,
        },
        {
          id: 3063,
          title:"DP 4",
          lastAssessed: "Jan 5, 2022",
          item: "",
          matiere: "",
          lastScore: 20,
        },
        {
          id: 3062,
          title:"DP 5",
          lastAssessed: "Jan 5, 2022",
          item: "154. Dissection Aortique",
          matiere: "",
          lastScore: 20,
        },
        {
          id: 3061,
          title:"DP 6",
          lastAssessed: "Jan 4, 2022",
          item: "",
          matiere: "",
          lastScore: 4,
        },
        {
          id: 3060,
          title:"LCA 1",
          lastAssessed: "",
          item: "",
          matiere: "",
          lastScore: null,
        },
        {
          id: 3059,
          title:"LCA 2",
          lastAssessed: "",
          item: "",
          matiere: "",
          lastScore: null,
        },
        {
          id: 3058,
          title:"DP 7",
          lastAssessed: "Jan 3, 2022",
          item: "",
          matiere: "",
          lastScore: 4,
        },
        {
          id: 3057,
          title:"DP 8",
          lastAssessed: "Jan 3, 2022",
          item: "",
          matiere: "",
          lastScore: 4,
        },
      ]
    },
    {
      title: "Pneumologie",
      num_questions: 22,
      dps : [
        {
          id: 3066,
          title:"DP 1",
          lastAssessed: "Jan 6, 2022",
          item: "",
          matiere: "",
          lastScore: 4,
        },
        {
          id: 3065,
          title:"DP 2",
          lastAssessed: "",
          item: "",
          matiere: "Cardiologie, Pneumologie, Néphrologie",
          lastScore: null,
        },
        {
          id: 3064,
          title:"DP 3",
          lastAssessed: "",
          item: "",
          matiere: "Cardiologie, Pneumologie, Néphrologie",
          lastScore: null,
        },
        {
          id: 3063,
          title:"DP 4",
          lastAssessed: "Jan 5, 2022",
          item: "",
          matiere: "",
          lastScore: 20,
        },
        {
          id: 3062,
          title:"DP 5",
          lastAssessed: "Jan 5, 2022",
          item: "154. Dissection Aortique",
          matiere: "",
          lastScore: 20,
        },
        {
          id: 3061,
          title:"DP 6",
          lastAssessed: "Jan 4, 2022",
          item: "",
          matiere: "",
          lastScore: 4,
        },
        {
          id: 3060,
          title:"LCA 1",
          lastAssessed: "",
          item: "",
          matiere: "",
          lastScore: null,
        },
        {
          id: 3059,
          title:"LCA 2",
          lastAssessed: "",
          item: "",
          matiere: "",
          lastScore: null,
        },
        {
          id: 3058,
          title:"DP 7",
          lastAssessed: "Jan 3, 2022",
          item: "",
          matiere: "",
          lastScore: 4,
        },
        {
          id: 3057,
          title:"DP 8",
          lastAssessed: "Jan 3, 2022",
          item: "",
          matiere: "",
          lastScore: 4,
        },
      ]
    },
    {
      title: "Oncologie",
      num_questions: 12,
      dps : [
        {
          id: 3066,
          title:"DP 1",
          lastAssessed: "Jan 6, 2022",
          item: "",
          matiere: "",
          lastScore: 4,
        },
        {
          id: 3065,
          title:"DP 2",
          lastAssessed: "",
          item: "",
          matiere: "Cardiologie, Pneumologie, Néphrologie",
          lastScore: null,
        },
        {
          id: 3064,
          title:"DP 3",
          lastAssessed: "",
          item: "",
          matiere: "Cardiologie, Pneumologie, Néphrologie",
          lastScore: null,
        },
        {
          id: 3063,
          title:"DP 4",
          lastAssessed: "Jan 5, 2022",
          item: "",
          matiere: "",
          lastScore: 20,
        },
        {
          id: 3062,
          title:"DP 5",
          lastAssessed: "Jan 5, 2022",
          item: "154. Dissection Aortique",
          matiere: "",
          lastScore: 20,
        },
        {
          id: 3061,
          title:"DP 6",
          lastAssessed: "Jan 4, 2022",
          item: "",
          matiere: "",
          lastScore: 4,
        },
        {
          id: 3060,
          title:"LCA 1",
          lastAssessed: "",
          item: "",
          matiere: "",
          lastScore: null,
        },
        {
          id: 3059,
          title:"LCA 2",
          lastAssessed: "",
          item: "",
          matiere: "",
          lastScore: null,
        },
        {
          id: 3058,
          title:"DP 7",
          lastAssessed: "Jan 3, 2022",
          item: "",
          matiere: "",
          lastScore: 4,
        },
        {
          id: 3057,
          title:"DP 8",
          lastAssessed: "Jan 3, 2022",
          item: "",
          matiere: "",
          lastScore: 4,
        },
      ]
    },
  ];
  return (
    <>
      <div className="inline-block min-w-full py-2 align-middle">
        <div className="flex flex-col gap-4">
          {categories.map((content, idx) => (
            <MatOrItem key={idx} content={content}/>
          ))}
        </div>
      </div>
    </>
  );
}

export default MatOrItems